### ISSUE TITLE
The FPS is not 30 but maybe 18?

### ISSUE THREAD

**Issue by ERICXUCHI** [BuildingVolumes/LiveScan3D#3]

**Comment by ERICXUCHI** [comment]
Hi, I am afraid that the FPS in the release version is only 18? Here I just recorded the frame number and the total time, it shows only about 18 fps.

![image](https://github.com/BuildingVolumes/LiveScan3D/assets/57583292/f86a7310-e2c0-472f-b074-9418222372a6)

**Comment by ERICXUCHI** [comment]
Perhaps there are some hardware or other problems that caused the fps not exactly equal to 30? I guess :）

**Comment by ChristopherRemde** [comment]
Hi, sorry for the late answer! 
Yes this is most likely caused due to not enough resources on the system. You can try to distribute the kinects between more PCs, so that each PC only serves one Kinect or upgrading your hardware (CPU most likely).

**Comment by ERICXUCHI** [comment]
Well received! Thanks!

**Comment by ChristopherRemde** [comment]
Just as an additional note: The lastest update on the dev branch should improve the performance by a larger margin, especially when you used multiple kinects in one client.
